const data = {
  products: [
    {
      id: 1,
      name: 'LV Bag 001',
      slug: 'LV Bag 001',
      category: 'Bags',
      image: '/images/p1a_lvbp.jpg', // 679px × 829px
      price: 1120,
      countInStock: 2,
      brand: 'LV',
      rating: 4.5,
      numReviews: 10,
      description: 'Top Grade Bag',
    },
    {
      id: 2,
      name: 'LV Bag 002',
      slug: 'LV Bag 002',
      category: 'Bags',
      image: '/images/p2a_lv_hb.jpg',
      price: 1250,
      countInStock: 20,
      brand: 'LV',
      rating: 4.0,
      numReviews: 10,
      description: 'Top Grade Bag',
    },
    {
      id: 3,
      name: 'Gucci Sling Bag 003',
      slug: 'Gucci Sling Bag 003',
      category: 'Bags',
      image: '/images/p3a_gucci_sling.jpg',
      price: 925,
      countInStock: 15,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 14,
      description: 'Top Grade Bag',
    },
    {
      id: 5,
      name: 'Tory Burch Tote Bag 004',
      slug: 'Tory Burch Tote Bag 004',
      category: 'Bags',
      image: '/images/p4a_tb_tote.jpg',
      price: 1565,
      countInStock: 5,
      brand: 'LV',
      rating: 4.5,
      numReviews: 10,
      description: 'Top Grade Bag',
    },
    {
      id: 6,
      name: 'Prada Yellow Belt Bag 005',
      slug: 'Prada Yellow Belt Bag 005',
      category: 'Bags',
      image: '/images/p5a-prada-yellow-belt-bag.jpg',
      price: 1150,
      countInStock: 5,
      brand: 'LV',
      rating: 4.5,
      numReviews: 10,
      description: 'Top Grade Bag',
    },
    {
      id: 7,
      name: 'Prada Belt Bag 006',
      slug: 'Prada Belt Bag 006',
      category: 'Bags',
      image: '/images/p6a-prada-belt-bag.jpg',
      price: 1900,
      countInStock: 5,
      brand: 'LV',
      rating: 4.5,
      numReviews: 10,
      description: 'Top Grade Bag',
    },
    {
      id: 8,
      name: 'Lacoste Yellow Tote Bag 007',
      slug: 'Lacoste Yellow Tote Bag 007',
      category: 'Bags',
      image: '/images/p7-lacoste_tote_bag_yellow.jpg',
      price: 650,
      countInStock: 10,
      brand: 'LV',
      rating: 4.5,
      numReviews: 10,
      description: 'Top Grade Bag',
    },
    {
      id: 9,
      name: 'Lacoste Green Tote Bag 008',
      slug: 'Lacoste Green Tote Bag 008',
      category: 'Bags',
      image: '/images/p8-lacoste-green.jpg',
      price: 650,
      countInStock: 8,
      brand: 'LV',
      rating: 4.5,
      numReviews: 10,
      description: 'Top Grade Bag',
    },
  ],
};
export default data;
